FROM mongo

ENV MONGO_INITDB_DATABASE=intelygenz
#ENV MONGO_INITDB_ROOT_USERNAME=admin
#ENV MONGO_INITDB_ROOT_PASSWORD=adminPASSWORD

COPY init_mongo.sh docker-entrypoint-initdb.d/
COPY data/restaurant.json /restaurant.json
